/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq;


import com.platform.chorus.jooq.tables.Collector;
import com.platform.chorus.jooq.tables.Entity;
import com.platform.chorus.jooq.tables.Field;
import com.platform.chorus.jooq.tables.Model;
import com.platform.chorus.jooq.tables.Relation;
import com.platform.chorus.jooq.tables.Value;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.collector</code>.
     */
    public static final Collector COLLECTOR = com.platform.chorus.jooq.tables.Collector.COLLECTOR;

    /**
     * The table <code>public.entity</code>.
     */
    public static final Entity ENTITY = com.platform.chorus.jooq.tables.Entity.ENTITY;

    /**
     * The table <code>public.field</code>.
     */
    public static final Field FIELD = com.platform.chorus.jooq.tables.Field.FIELD;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = com.platform.chorus.jooq.tables.Model.MODEL;

    /**
     * The table <code>public.relation</code>.
     */
    public static final Relation RELATION = com.platform.chorus.jooq.tables.Relation.RELATION;

    /**
     * The table <code>public.value</code>.
     */
    public static final Value VALUE = com.platform.chorus.jooq.tables.Value.VALUE;
}
