/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collector implements Serializable {

    private static final long serialVersionUID = 474990075;

    private Integer  id;
    private String   name;
    private String   result;
    private String[] injects;
    private String[] args;
    private String   description;

    public Collector() {}

    public Collector(Collector value) {
        this.id = value.id;
        this.name = value.name;
        this.result = value.result;
        this.injects = value.injects;
        this.args = value.args;
        this.description = value.description;
    }

    public Collector(
        Integer  id,
        String   name,
        String   result,
        String[] injects,
        String[] args,
        String   description
    ) {
        this.id = id;
        this.name = name;
        this.result = result;
        this.injects = injects;
        this.args = args;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String[] getInjects() {
        return this.injects;
    }

    public void setInjects(String... injects) {
        this.injects = injects;
    }

    public String[] getArgs() {
        return this.args;
    }

    public void setArgs(String... args) {
        this.args = args;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Collector (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(result);
        sb.append(", ").append(Arrays.toString(injects));
        sb.append(", ").append(Arrays.toString(args));
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
