/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entity implements Serializable {

    private static final long serialVersionUID = -1777476414;

    private Integer   id;
    private String    name;
    private String    type;
    private String    creator;
    private Integer[] associate;
    private String[]  tags;
    private Integer   grade;
    private Long      createTime;
    private Long      updateTime;
    private String    description;

    public Entity() {}

    public Entity(Entity value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.creator = value.creator;
        this.associate = value.associate;
        this.tags = value.tags;
        this.grade = value.grade;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.description = value.description;
    }

    public Entity(
        Integer   id,
        String    name,
        String    type,
        String    creator,
        Integer[] associate,
        String[]  tags,
        Integer   grade,
        Long      createTime,
        Long      updateTime,
        String    description
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.creator = creator;
        this.associate = associate;
        this.tags = tags;
        this.grade = grade;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public Integer[] getAssociate() {
        return this.associate;
    }

    public void setAssociate(Integer... associate) {
        this.associate = associate;
    }

    public String[] getTags() {
        return this.tags;
    }

    public void setTags(String... tags) {
        this.tags = tags;
    }

    public Integer getGrade() {
        return this.grade;
    }

    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(creator);
        sb.append(", ").append(Arrays.toString(associate));
        sb.append(", ").append(Arrays.toString(tags));
        sb.append(", ").append(grade);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
