/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Field implements Serializable {

    private static final long serialVersionUID = 40082667;

    private Integer id;
    private String  owner;
    private String  name;
    private String  type;
    private String  label;
    private String  collector;
    private String  relation;
    private String  constraints;
    private String  description;

    public Field() {}

    public Field(Field value) {
        this.id = value.id;
        this.owner = value.owner;
        this.name = value.name;
        this.type = value.type;
        this.label = value.label;
        this.collector = value.collector;
        this.relation = value.relation;
        this.constraints = value.constraints;
        this.description = value.description;
    }

    public Field(
        Integer id,
        String  owner,
        String  name,
        String  type,
        String  label,
        String  collector,
        String  relation,
        String  constraints,
        String  description
    ) {
        this.id = id;
        this.owner = owner;
        this.name = name;
        this.type = type;
        this.label = label;
        this.collector = collector;
        this.relation = relation;
        this.constraints = constraints;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getCollector() {
        return this.collector;
    }

    public void setCollector(String collector) {
        this.collector = collector;
    }

    public String getRelation() {
        return this.relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public String getConstraints() {
        return this.constraints;
    }

    public void setConstraints(String constraints) {
        this.constraints = constraints;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Field (");

        sb.append(id);
        sb.append(", ").append(owner);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(label);
        sb.append(", ").append(collector);
        sb.append(", ").append(relation);
        sb.append(", ").append(constraints);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
