/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Value implements Serializable {

    private static final long serialVersionUID = 1584270339;

    private Integer id;
    private Integer owner;
    private String  name;
    private String  type;
    private String  value;

    public Value() {}

    public Value(Value value) {
        this.id = value.id;
        this.owner = value.owner;
        this.name = value.name;
        this.type = value.type;
        this.value = value.value;
    }

    public Value(
        Integer id,
        Integer owner,
        String  name,
        String  type,
        String  value
    ) {
        this.id = id;
        this.owner = owner;
        this.name = name;
        this.type = type;
        this.value = value;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOwner() {
        return this.owner;
    }

    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Value (");

        sb.append(id);
        sb.append(", ").append(owner);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
