/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables;


import com.platform.chorus.jooq.Keys;
import com.platform.chorus.jooq.Public;
import com.platform.chorus.jooq.tables.records.RelationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relation extends TableImpl<RelationRecord> {

    private static final long serialVersionUID = -2102929003;

    /**
     * The reference instance of <code>public.relation</code>
     */
    public static final Relation RELATION = new Relation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelationRecord> getRecordType() {
        return RelationRecord.class;
    }

    /**
     * The column <code>public.relation.id</code>.
     */
    public final TableField<RelationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('relation_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.relation.name</code>.
     */
    public final TableField<RelationRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.relation.creator</code>.
     */
    public final TableField<RelationRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.relation.description</code>.
     */
    public final TableField<RelationRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.relation</code> table reference
     */
    public Relation() {
        this(DSL.name("relation"), null);
    }

    /**
     * Create an aliased <code>public.relation</code> table reference
     */
    public Relation(String alias) {
        this(DSL.name(alias), RELATION);
    }

    /**
     * Create an aliased <code>public.relation</code> table reference
     */
    public Relation(Name alias) {
        this(alias, RELATION);
    }

    private Relation(Name alias, Table<RelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relation(Name alias, Table<RelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RelationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RELATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RelationRecord> getPrimaryKey() {
        return Keys.RELATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RelationRecord>> getKeys() {
        return Arrays.<UniqueKey<RelationRecord>>asList(Keys.RELATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relation as(String alias) {
        return new Relation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relation as(Name alias) {
        return new Relation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Relation rename(String name) {
        return new Relation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Relation rename(Name name) {
        return new Relation(name, null);
    }
}
