/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.daos;


import com.platform.chorus.jooq.tables.Model;
import com.platform.chorus.jooq.tables.records.ModelRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelDao extends DAOImpl<ModelRecord, com.platform.chorus.jooq.tables.pojos.Model, Integer> {

    /**
     * Create a new ModelDao without any configuration
     */
    public ModelDao() {
        super(Model.MODEL, com.platform.chorus.jooq.tables.pojos.Model.class);
    }

    /**
     * Create a new ModelDao with an attached configuration
     */
    public ModelDao(Configuration configuration) {
        super(Model.MODEL, com.platform.chorus.jooq.tables.pojos.Model.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.jooq.tables.pojos.Model object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchById(Integer... values) {
        return fetch(Model.MODEL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.platform.chorus.jooq.tables.pojos.Model fetchOneById(Integer value) {
        return fetchOne(Model.MODEL.ID, value);
    }

    /**
     * Fetch records that have <code>domain IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchByDomain(String... values) {
        return fetch(Model.MODEL.DOMAIN, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchByName(String... values) {
        return fetch(Model.MODEL.NAME, values);
    }

    /**
     * Fetch records that have <code>extend IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchByExtend(String... values) {
        return fetch(Model.MODEL.EXTEND, values);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchByLabel(String... values) {
        return fetch(Model.MODEL.LABEL, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Model> fetchByDescription(String... values) {
        return fetch(Model.MODEL.DESCRIPTION, values);
    }
}
