/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.jooq.tables.daos;


import com.platform.chorus.jooq.tables.Relation;
import com.platform.chorus.jooq.tables.records.RelationRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelationDao extends DAOImpl<RelationRecord, com.platform.chorus.jooq.tables.pojos.Relation, Integer> {

    /**
     * Create a new RelationDao without any configuration
     */
    public RelationDao() {
        super(Relation.RELATION, com.platform.chorus.jooq.tables.pojos.Relation.class);
    }

    /**
     * Create a new RelationDao with an attached configuration
     */
    public RelationDao(Configuration configuration) {
        super(Relation.RELATION, com.platform.chorus.jooq.tables.pojos.Relation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.jooq.tables.pojos.Relation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Relation> fetchById(Integer... values) {
        return fetch(Relation.RELATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.platform.chorus.jooq.tables.pojos.Relation fetchOneById(Integer value) {
        return fetchOne(Relation.RELATION.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Relation> fetchByName(String... values) {
        return fetch(Relation.RELATION.NAME, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Relation> fetchByCreator(String... values) {
        return fetch(Relation.RELATION.CREATOR, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.jooq.tables.pojos.Relation> fetchByDescription(String... values) {
        return fetch(Relation.RELATION.DESCRIPTION, values);
    }
}
